### ISSUE TITLE
Calculation of hospitalized

### ISSUE THREAD

**Issue by vleotti** [misken/c19#2]
Hi,
thank you for this notebook. It is very useful for me. I have a doubt about this part:

"Finally, we can get to dispositions by multiplying $S_t^{'}$ by the appropriate resource use rate for hospitalization ($h=$ hospitalized-rate) and the hospital market share ($m =$ market-share). For hospitalizations,

$$
D_t^{H} = h \cdot m \cdot S_t^{'}
$$"

I think that $i_t$ should me multiplied by market share and hospitalization rate, isn't it? Beign
D_t^{H} = h \cdot m \cdot i_t^

Thanks,
Vanessa

**Comment by misken** [comment]
That's actually what ends up happening. The way that the code is written, they are just multiplying $h$ by $m$ by $S_t$ to get $D_t$ and calling it "dispositions". Then in later step when admits is calculated via  $D_t - D_{t-1}$ you are essentially doing $h \cdot m \cdot i_t$.

My code screenshot is actually from older code. They've refactored things to speed up the computations. So now if you look at the bottom of the `sim_sir()` function in models.py you'll see code that looks like this:

`return {
        "day": d_a,
        "susceptible": s_a,
        "infected": i_a,
        "recovered": r_a,
        "ever_infected": i_a + r_a
    }`

That "ever_infected" key is $S^{'}$ It's I_t + R_t, which is needed to account for the flow of some of I into R during t to t+1. Then if you look further down, in the `calculate_dispositions()` function, you'll see (key is just "hospitalized", "icu" or "ventilated":

`raw["ever_" + key] = raw["ever_infected"] * rate * market_share`

Again, h times m times S-prime. Yep, it took me a while to sort it out too and you aren't the first person to ask about this. Hope this helps.

**Comment by vleotti** [comment]
Thank you very much! I would not understand this alone.



Em qui, 9 de abr de 2020 19:30, Mark Isken <notifications@github.com>
escreveu:

**Comment by misken** [comment]
Glad I could help.
